### ISSUE TITLE
how to run the layerdiffusion model in ComfyUI?

### ISSUE THREAD

**Issue by marvin521** [huchenlei/ComfyUI-layerdiffusion#10]
I am a newbie to ComfyUI. I can start ComfyUI now, but how can I use your code in ComfyUI?

**Comment by huchenlei** [comment]
Thanks for reminding! I have updated README to include a more detailed installation guide https://github.com/huchenlei/ComfyUI-layerdiffusion/blob/main/README.md#installation

**Comment by marvin521** [comment]
> Thanks for reminding! I have updated README to include a more detailed installation guide https://github.com/huchenlei/ComfyUI-layerdiffusion/blob/main/README.md#installation

Efficient and timely reply, thank you
