### ISSUE TITLE
M1 Running this node reported an error, please help to solve it, thank you very much!

### ISSUE THREAD

**Issue by yiwangsimple** [huchenlei/ComfyUI-layerdiffusion#11]
/AppleInternal/Library/BuildRoots/2acced82-df86-11ed-9b95-428477786501/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSNDArray/Kernels/MPSNDArraySort.mm:283: failed assertion `(null)" Axis = 4. This class only supports axis = 0, 1, 2, 3
'
Abort trap: 6
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown

**Comment by huchenlei** [comment]
Duplicated. See #1.
