### ISSUE TITLE
SDXL Lightning produces terrible results 

### ISSUE THREAD

**Issue by camoody1** [huchenlei/ComfyUI-layerdiffusion#14]
I tried your sample workflow using an SDXL Lightning model and the results were really quite bad. When I switched to a standard SDXL model, the result was much better. Is this something you expect? Have you tried a lightning model yourself?

Thank you for your work.

**Comment by huchenlei** [comment]
I think you can report this issue in the LayerDiffusion main repo: https://github.com/layerdiffusion/LayerDiffusion/issues. I don't think the worse quality on distilled SDXL model is caused by the ComfyUI-specific impl.
