### ISSUE TITLE
Same setting, but the output is totally different image.  fixed seed, same ksampler

### ISSUE THREAD

**Issue by n714** [huchenlei/ComfyUI-layerdiffusion#5]
![workflow](https://github.com/huchenlei/ComfyUI-layerdiffusion/assets/45053630/044eeac0-2bf9-4e5d-89fd-74f56b2e7f66)

**Comment by huchenlei** [comment]
I think is the limitation of https://github.com/layerdiffusion/LayerDiffusion. Layer diffusion is essentially adding a LoRA to conv/attn layers of the model. It is not surprising that you get different images with fixed seed but with/without LoRA applied.

**Comment by n714** [comment]
I also tested on forge version, in same condition. it does show the same image out in transparent , do you meant it's the comfyui issue?

**Comment by huchenlei** [comment]
SD Forge

## Without layer diffusion:
![image](https://github.com/huchenlei/ComfyUI-layerdiffusion/assets/20929282/8f94f4d0-9c02-4ba1-a060-c39814af3fa8)

## With layer diffusion:
![image](https://github.com/huchenlei/ComfyUI-layerdiffusion/assets/20929282/731ddf6c-cf73-49ea-aa59-7ab36a15616c)
![image](https://github.com/huchenlei/ComfyUI-layerdiffusion/assets/20929282/4b2cf6cd-cdfc-4e03-a43c-f1a9951e19ef)


## Conclusion
I do not think is issue is specific to the ComfyUI implementation.

**Comment by n714** [comment]
![1](https://github.com/huchenlei/ComfyUI-layerdiffusion/assets/45053630/40a0b9c7-93f5-444f-8c30-9dc981064f1e)
![2](https://github.com/huchenlei/ComfyUI-layerdiffusion/assets/45053630/06b2894b-1fe8-4510-9356-8423735fff2e)

**Comment by n714** [comment]
yes, there is a little bit different
