### ISSUE TITLE
Join Image with Alpha node

### ISSUE THREAD

**Issue by nomadoor** [huchenlei/ComfyUI-layerdiffusion#6]
[![Image from Gyazo](https://i.gyazo.com/66c35cf05360ca311837feca42786028.png)](https://gyazo.com/66c35cf05360ca311837feca42786028)
In the sample workflow, `Apply Mask to Image` is used to create a transparent image from an RGB image and a mask. However, ComfyUI has a default node called `Join Image with Alpha` that can do the same thing.

It’s a minor issue, but this might be a better choice for the sample.

**Comment by huchenlei** [comment]
Done in https://github.com/huchenlei/ComfyUI-layerdiffusion/commit/f6191954a51ce3b20c5d4976fb3a54c70e4098af. Workflow modified, and I added `Layer Diffusion Decode (RGBA)` to output image with transparent background in single step.

**Comment by nomadoor** [comment]
Being able to export directly as an RGBA image is cool!
Thanks for the good work.
